#!/bin/bash
#-------------------
# Testing freeradius
#-------------------
set -e
DAEMON=freeradius

if pidof -x $DAEMON > /dev/null; then
    echo "OK"
else
    echo "ERROR: ${DAEMON} IS NOT RUNNING"
    exit 1
fi
